image: node
pipelines:
  branches:
    master:
      - step:
          name: Install dependencies and build
          script:
            - yarn && yarn prepare && yarn build
      - step:
          name: Deploy to cloudflare
          deployment: Production
          script:
            - npm i -g wrangler
            - wrangler pages publish dist --project-name messenger
