image: node
pipelines:
  branches:
    master:
      - step:
          name: Deploy to cloudflare
          script:
            - echo "Install dependencies and build"
            - yarn && yarn prepare && yarn build
            - echo "Install wrangler"
            - npm i -g wrangler
            - echo "Deploy to cloudflare"
            - wrangler pages publish ./dist --project-name messenger
            
